-- Calculate total revenue generated from all orders
SELECT SUM(payment_value) AS total_revenue
FROM payments;

-- Count total number of orders placed
SELECT 
    COUNT(order_id) AS total_orders
FROM orders;

-- Find average payment value per order
SELECT AVG(payment_value) AS avg_order_value
FROM payments;

-- Analyze how many orders are delivered, shipped, or cancelled
SELECT order_status, COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;

-- Identify which payment method customers prefer
SELECT payment_type, COUNT(*) AS total_transactions
FROM payments
GROUP BY payment_type
ORDER BY total_transactions DESC;

-- Find how many units of each product were sold
SELECT product_id, SUM(quantity) AS total_quantity
FROM order_items
GROUP BY product_id
ORDER BY total_quantity DESC;

-- Calculate revenue generated by each order
SELECT order_id, SUM(payment_value) AS order_revenue
FROM payments
GROUP BY order_id;

-- Identify how many orders each customer placed
SELECT customer_id, COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC;

-- Show order details along with payment value
SELECT o.order_id, o.customer_id, p.payment_value
FROM orders o
JOIN payments p
ON o.order_id = p.order_id;

-- Show which products were sold in each order
SELECT o.order_id, oi.product_id, oi.quantity
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id;

-- Rank orders based on payment value
SELECT order_id, payment_value,
RANK() OVER (ORDER BY payment_value DESC) AS payment_rank
FROM payments;

-- Calculate cumulative revenue across orders
SELECT order_id,
SUM(payment_value) OVER (ORDER BY order_id) AS running_total_revenue
FROM payments;

-- Retrieve top 5 orders with highest payment value
SELECT *
FROM payments
ORDER BY payment_value DESC
LIMIT 5;



